name: llvm
version: 0.0.7
description: Support for generating LLVM IR, and using the LLVM toolchain within Dart.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/llvm
environment:
  sdk: ">=1.19.0"
dependencies:
  indenting_buffer: ^1.0.0
  meta: ^1.0.0
  process: ^2.0.0
  random_string: ^0.0.1